host = 'localhost'
username = 'postgres'
pass_word = '189213'
port = 5432
driver = 'ct'
get_roots = 'https://{}'
subject = {
    'subject_country_name': 'NA',
    'subject_organization_name': 'NA',
    'subject_common_name': 'NA',
    'subject_email': 'NA',
    'algorithm': 'NA',
    'sha1': 'NA',
    'sha256': 'NA',
    'issuer_country_name': 'NA',
    'issuer_organization_name': 'NA',
    'issuer_common_name': 'NA',
    'issuer_email': 'NA',
    'subject_state_or_province_name': 'NA',
    'subject_locality_name': 'NA',
    'subject_email_address': 'NA',
    'issuer_state_or_province_name': 'NA',
    'issuer_locality_name': 'NA',
    'issuer_email_address': 'NA',
    'subject_organizational_unit_name': 'NA',
    'issuer_organizational_unit_name': 'NA',
    'subject_DPA': 'NA',
    'issuer_DPA': 'NA',
    'serial_number': 'NA',
    'subject_serial_number': 'NA',
    'issuer_serial_number': 'NA',
    'subject_domain_component': 'NA',
    'issuer_domain_component': 'NA',
    'issuer_street_address': 'NA',
    'subject_street_address': 'NA',
    'subject_organization_identifier': 'NA',
    'issuer_organization_identifier': 'NA',
    'subject_postal_code': 'NA',
    'issuer_postal_code': 'NA',
    'subject_unique_identifier': 'NA',
    'issuer_unique_identifier': 'NA',
    'subject_incorporation_locality': 'NA',
    'subject_incorporation_country': 'NA',
    'subject_incorporation_state_or_province': 'NA',
    'subject_business_category': 'NA',
    'subject_postOfficeBox': 'NA',
    'issuer_houseIdentifier': 'NA',
    'subject_dn_qualifier': 'NA',
    'not_before': 'NA',
    'not_after': 'NA',
    'subject_unstructuredName': 'NA',
    'subject_userid': 'NA',
    'subject_given_name': 'NA',
    'subject_surname': 'NA',
    'subject_unstructuredAddress': 'NA',
    'subject_postalAddress': 'NA',
    'subject_pseudonym': 'NA'
}
